### PR TITLE
Set firewall rules outside openvpn connection

### PR DESCRIPTION
**Pull request by hidrarga**
## Problem

I discussed about this with @zamentur : the idea is to keep the firewall rules even when the VPN is disconnected. The client should still be able to reconnect, because there are rules allowing everything coming from the VPN server.

Some reasons about that:
- If the scripts takes too long, the server might timeout the connection, and the client will enter in a loop of reconnection. By removing the script where we set the firewall rules, the client will be a bit faster to connect.
- If the user has the hotspot app, we want them to go through the VPN. 

A problem with this approach is that the user won't have access to internet until the VPN is up again...

## Solution

I'm setting the firewall rules in the ynh-vpnclient service, as it was before. So the firewall rules won't be removed when the VPN is down.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by hidrarga** [comment]
Also, about the timeout thing, the `keepalive` directive must be high, otherwise the connection will timeout. However, when I set `keepalive 10 120`, which means "timeout after 120 seconds of inactivity", I'm still getting an error saying "TLS handshake timeout (failed to occur in 60 seconds". So I guess there are other directives to adapt…

However, I also noticed some weird behavior with DNS resolution when the VPN is reconnecting: When it happens, I'm unable to resolve DNS because it timeouts… But I can't always reproduce this bug... So I'll probably make another PR to make all the DNS resolution part outside the VPN connection as well.

**Comment by ericgaspar** [comment]
!testme

**Comment by hidrarga** [comment]
I'm not super convinced about this, because it makes things complicated (that's why I moved firewall configuration to hook scripts some months ago).

Where should we configure firewall rules? Before starting the openvpn client?  or should we do it after starting the client ? But then, what happens if the client fails to connect for some reasons? In the first case we might be stuck with a server that can't reach internet (except the VPN server). In the second case, we might have a VPN without the firewall rules configured...

**Comment by hidrarga** [comment]
I'm closing for the reasons I said above, it raises more questions than anything else

**Pull request closed without merging**
