### PR TITLE
fix parsing .ovpn

### PR DESCRIPTION
**Pull request by jerometerrier**
#100 

## Problem

- I made this PR because, as explained in #100 , ovpn file is not working well.
We obtain : 
```
</tls-crypt>ca /etc/openvpn/keys/ca-server.crt
cert /etc/openvpn/keys/user.crt
key /etc/openvpn/keys/user.key
```
instead of 

```
</tls-crypt>
ca /etc/openvpn/keys/ca-server.crt
cert /etc/openvpn/keys/user.crt
key /etc/openvpn/keys/user.key
```

My solution give this result : 
```
</tls-crypt>
ca /etc/openvpn/keys/ca-server.crt

cert /etc/openvpn/keys/user.crt

key /etc/openvpn/keys/user.key
```

I just tested it on dev installation. Working well 👍

### CODE REVIEW

**Comment by jerometerrier** [comment]
!testme

**Comment by jerometerrier** [comment]
@zamentur , @Psycojoker , @NicolasPetton , @sbadia   
Could you please have a look ?  
Thank you :)

**Comment by HugoPoi** [comment]
Looking good to me, can we merge that ?

**Comment by jerometerrier** [comment]
Hello @alexAubin 
Seems you were the last one who merged something in this repo.
Could you help please ? :)
Thank you

**Pull request merged**
