### PR TITLE
Testing | Packaging v2 + generate config during upgrade + Add hook scripts

### PR DESCRIPTION
**Pull request by alexAubin**
- https://github.com/YunoHost-Apps/vpnclient_ynh/pull/113
- https://github.com/YunoHost-Apps/vpnclient_ynh/pull/116
- https://github.com/YunoHost-Apps/vpnclient_ynh/pull/118

### CODE REVIEW

**Comment by alexAubin** [comment]
!testme

**Comment by alexAubin** [comment]
!testme

**Comment by alexAubin** [comment]
(can't approve my own PR but LGTM)

**Comment by hidrarga** [comment]
I noticed that the VPN wasn't restarted after upgrade, here are the logs:
```
  - Nov 19 22:55:21 systemd[1]: Stopping YunoHost VPN Client....
  - Nov 19 22:55:21 ynh-vpnclient[27023]: [INFO] Retrieving Yunohost settings...
  - Nov 19 22:55:21 ynh-vpnclient[27072]: [ OK ] Settings retrieved
  - Nov 19 22:55:21 ynh-vpnclient[27074]: [INFO] [vpnclient] Stopping...
  - Nov 19 22:55:21 ynh-vpnclient[27088]: [INFO] Cleaning vpnclient custom rules from the firewall
  - Nov 19 22:55:21 ynh-vpnclient[27091]: [INFO] Restarting yunohost firewall...
  - Nov 19 22:55:39 ynh-vpnclient[27092]: Another YunoHost command is running right now, we are waiting for it to finish before running this one
  - Nov 19 22:56:24 ynh-vpnclient[27092]: Still waiting...
  - Nov 19 22:56:51 systemd[1]: ynh-vpnclient.service: Stopping timed out. Terminating.
  - Nov 19 22:56:51 systemd[1]: ynh-vpnclient.service: Control process exited, code=killed, status=15/TERM
  - Nov 19 22:56:51 systemd[1]: ynh-vpnclient.service: Failed with result 'timeout'.
  - Nov 19 22:56:51 systemd[1]: Stopped YunoHost VPN Client..
  - Nov 19 22:56:51 systemd[1]: ynh-vpnclient.service: Consumed 3.591s CPU time.
  - Nov 19 22:56:51 systemd[1]: Starting YunoHost VPN Client....
  - Nov 19 22:56:51 ynh-vpnclient[27265]: [INFO] Retrieving Yunohost settings...
  - Nov 19 22:56:51 ynh-vpnclient[27314]: [ OK ] Settings retrieved
  - Nov 19 22:56:52 ynh-vpnclient[27338]: [INFO] Service is already running
  - Nov 19 22:56:52 systemd[1]: Finished YunoHost VPN Client..
```

**Comment by hidrarga** [comment]
!testme

**Comment by alexAubin** [comment]
@hidrarga : can't approve my own PR but LGTM, shall we merge this ? There's also https://github.com/YunoHost-Apps/vpnclient_ynh/pull/120 which could be merged/released now or later

**Comment by alexAubin** [comment]
!testme

**Comment by hidrarga** [comment]
> @hidrarga : can't approve my own PR but LGTM, shall we merge this ? There's also #120 which could be merged/released now or later

I noticed some bug when the VPN disconnects : the client is failing in a loop, because it can't resolve anymore the DNS of the VPN server... I'd like to do some more testing to understand what's causing this, and hopefully solve it.

**Comment by hidrarga** [comment]
> > @hidrarga : can't approve my own PR but LGTM, shall we merge this ? There's also #120 which could be merged/released now or later
> 
> I noticed some bug when the VPN disconnects : the client is failing in a loop, because it can't resolve anymore the DNS of the VPN server... I'd like to do some more testing to understand what's causing this, and hopefully solve it.

I was able to reproduce the bug a couple of months ago, but now that I had (finally) time to test it further, I'm unable to reproduce the bug... So I'd say let's merge, maybe the problem has been solved magically :shrug:

**Pull request merged**
